packages:
  - trainer
  - packages/*
  - miniapp

allowBuilds:
  esbuild: true
  "@parcel/watcher": true
  "@swc/core": true
  "@tarojs/binding": true
  core-js: false
  core-js-pure: false
  '@tarojs/cli': true

overrides:
  webpack: 5.91.0
