#!/usr/bin/env python3
"""Create/check the public Rime ZIP against ALL generated bytes plus notices."""
import argparse
from pathlib import Path
import stat
import zipfile
from check_generated_runtime_sources import MODULES, verify as verify_runtime

YAML = (
    "xhup_flow", "xhup_flow_static", "xhup_flow_flow", "xhup_flow_learn",
)
DICTIONARIES = (
    "xhup_flow", "xhup_flow_chars", "xhup_flow_words", "xhup_flow_shortcuts",
    "xhup_flow_word_shortcuts", "xhup_flow_fixed_first_shortcuts",
    "xhup_flow_flow", "xhup_flow_learn",
)
GENERATED = ({f"{name}.schema.yaml" for name in YAML}
             | {f"{name}.dict.yaml" for name in DICTIONARIES}
             | {f"lua/xhup_flow/{name}.lua" for name in MODULES}
             | {"lua/xhup_flow/data/quick_hints.lua", "xhup_flow.sources.tsv", "default.custom.yaml"})
NOTICES = {
    "INSTALL.md": "rime/package/INSTALL.md",
    "NOTICE.md": "rime/package/NOTICE.md",
    "licenses/project-LGPL-3.0.txt": "LICENSE",
    "licenses/GPL-3.0.txt": "LICENSE.GPL-3.0",
    "licenses/wanxiang-CC-BY-4.0.txt": "data/words/LICENSE.wanxiang",
    "licenses/pinyin-data-MIT.txt": "data/hanzi/LICENSE.pinyin-data",
    "licenses/kdconv-Apache-2.0.txt": "data/corpus/LICENSE.kdconv",
    "licenses/ptt-Apache-2.0.txt": "data/corpus/LICENSE.ptt",
}


def payloads(package, root):
    actual = set()
    for path in package.rglob("*"):
        if path.is_symlink():
            raise ValueError(f"symlink in generated package: {path}")
        if path.is_file():
            actual.add(path.relative_to(package).as_posix())
    if actual != GENERATED:
        raise ValueError(f"generated inventory mismatch: missing={GENERATED-actual}, extra={actual-GENERATED}")
    verify_runtime(package, root)
    if (package / "default.custom.yaml").read_bytes() != (root / "rime/package/default.custom.yaml").read_bytes():
        raise ValueError("exclusive schema configuration differs from canonical source")
    policy = (b"# distribution-policy=clean-v1\n"
              b"# research-only sources are metadata only; their payloads are excluded\n"
              + (root / "data/xhup/sources.tsv").read_bytes())
    if (package / "xhup_flow.sources.tsv").read_bytes() != policy:
        raise ValueError("source policy bytes do not match registry")
    paths = {name: package / name for name in GENERATED}
    paths.update({name: root / source for name, source in NOTICES.items()})
    if any(not path.is_file() or path.is_symlink() or path.stat().st_size == 0
           for path in paths.values()):
        raise ValueError("missing/empty/unsafe package file or notice")
    return paths


def check(archive, paths):
    with zipfile.ZipFile(archive) as zipped:
        names = zipped.namelist()
        if len(names) != len(set(names)) or set(names) != set(paths):
            raise ValueError("archive inventory mismatch or duplicate name")
        for name, source in paths.items():
            if zipped.read(name) != source.read_bytes():
                raise ValueError(f"archive byte mismatch: {name}")
    return len(paths)


def create(archive, paths):
    # Exclusive output and fixed metadata: no stale archive update or timestamp drift.
    with zipfile.ZipFile(archive, "x", compression=zipfile.ZIP_DEFLATED) as zipped:
        for name, source in sorted(paths.items()):
            info = zipfile.ZipInfo(name, date_time=(1980, 1, 1, 0, 0, 0))
            info.create_system = 3
            info.external_attr = (stat.S_IFREG | 0o644) << 16
            info.compress_type = zipfile.ZIP_DEFLATED
            zipped.writestr(info, source.read_bytes(), compresslevel=9)
    return check(archive, paths)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("mode", choices=("verify", "create", "check"))
    parser.add_argument("package", type=Path)
    parser.add_argument("archive", type=Path, nargs="?")
    args = parser.parse_args()
    if args.mode != "verify" and args.archive is None:
        parser.error("create/check require an archive path")
    paths = payloads(args.package, Path(__file__).resolve().parents[2])
    if args.mode == "verify":
        print(f"PASS Rime package: {len(GENERATED)} exact generated files; all notices present")
        return
    count = (create if args.mode == "create" else check)(args.archive, paths)
    print(f"PASS Rime archive: {count} exact generated/document/license file identities")


if __name__ == "__main__":
    main()
