"""Synthetic archive regressions; actual generated bytes are checked in packaging."""
import hashlib
import json
from pathlib import Path
import shutil
import tempfile
import unittest
import zipfile
import rime_archive as archive

ROOT = Path(__file__).resolve().parents[2]


class RimeArchive(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory()
        self.addCleanup(self.temp.cleanup)
        self.work = Path(self.temp.name)
        self.package = self.work / "package"
        self.package.mkdir()
        for name in archive.GENERATED:
            path = self.package / name
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(b"synthetic dictionary\n")
        for name in archive.MODULES:
            rel = f"lua/xhup_flow/{name}.lua"
            shutil.copyfile(ROOT / "rime" / rel, self.package / rel)
        import tomllib
        version = tomllib.loads((ROOT / "Cargo.toml").read_text())["workspace"]["package"]["version"]
        for name in ("xhup_flow", "xhup_flow_static"):
            (self.package / f"{name}.schema.yaml").write_bytes(
                (ROOT / f"rime/templates/{name}.schema.yaml.in").read_bytes().replace(
                    b"{{VERSION}}", version.encode()))
        (self.package / "xhup_flow.sources.tsv").write_bytes(
            b"# distribution-policy=clean-v1\n"
            b"# research-only sources are metadata only; their payloads are excluded\n"
            + (ROOT / "data/xhup/sources.tsv").read_bytes())
        self.paths = archive.payloads(self.package, ROOT)
        self.zip = self.work / "package.zip"
        archive.create(self.zip, self.paths)

    def test_all_generated_files_not_just_yaml_lua_and_determinism(self):
        self.assertEqual(archive.check(self.zip, self.paths), 30)
        other = self.work / "second.zip"
        archive.create(other, self.paths)
        self.assertEqual(self.zip.read_bytes(), other.read_bytes())
        with self.assertRaises(FileExistsError):
            archive.create(self.zip, self.paths)

    def test_missing_policy_or_notice_and_modified_member(self):
        for missing in ("xhup_flow.sources.tsv", "NOTICE.md",
                        "licenses/pinyin-data-MIT.txt"):
            out = self.work / "missing.zip"
            with zipfile.ZipFile(out, "w") as zipped:
                for name, source in self.paths.items():
                    if name != missing:
                        zipped.writestr(name, source.read_bytes())
            with self.assertRaises(ValueError):
                archive.check(out, self.paths)
        out = self.work / "changed.zip"
        with zipfile.ZipFile(out, "w") as zipped:
            for name, source in self.paths.items():
                zipped.writestr(name, source.read_bytes() + b"changed")
        with self.assertRaises(ValueError):
            archive.check(out, self.paths)

    def test_private_or_unknown_generated_file_fails(self):
        for name in ("user.yaml", "installation.yaml", "secrets.txt",
                     "xhup_flow_user.userdb/CURRENT"):
            path = self.package / name
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text("private")
            with self.assertRaises(ValueError):
                archive.payloads(self.package, ROOT)
            path.unlink()

    def test_missing_and_replaced_policy(self):
        policy = self.package / "xhup_flow.sources.tsv"
        policy.unlink()
        with self.assertRaises(ValueError):
            archive.payloads(self.package, ROOT)
        policy.write_text("false-policy")
        with self.assertRaises(ValueError):
            archive.payloads(self.package, ROOT)

    def test_unsafe_symlink_and_unexpected_zip_member(self):
        path = self.package / "xhup_flow.dict.yaml"
        path.unlink()
        path.symlink_to(ROOT / "LICENSE")
        with self.assertRaises(ValueError):
            archive.payloads(self.package, ROOT)
        with zipfile.ZipFile(self.zip, "a") as zipped:
            zipped.writestr("../user.yaml", "private")
        with self.assertRaises(ValueError):
            archive.check(self.zip, self.paths)

    def test_notices_bound_to_binary_resources_and_pinned_upstream(self):
        config = ROOT / "trainer/src-tauri/tauri.conf.json"
        resources = json.loads(config.read_text())["bundle"]["resources"]
        for name, source in archive.NOTICES.items():
            if name in ("INSTALL.md", "NOTICE.md"):
                continue
            self.assertEqual(resources["../../" + source], name)
        self.assertEqual(resources["../../rime/package/NOTICE.md"],
                         "licenses/RIME-DATA-NOTICE.md")
        notice = ROOT / "data/hanzi/LICENSE.pinyin-data"
        self.assertEqual(hashlib.sha256(notice.read_bytes()).hexdigest(),
                         "9c048697be2502a16e8bcb282d5d465a07295b2def0ffb05a269c5d39dbe1586")

    def test_workflow_checks_final_archive_bytes(self):
        text = (ROOT / ".github/workflows/product-packaging.yml").read_text()
        section = text.split("      - name: 组装发布 zip", 1)[1].split(
            "      - name: 上传 Rime 源包产物", 1)[0]
        self.assertIn("rime_archive.py create build/rime-package", section)
        self.assertIn("rime_archive.py check build/rime-package", section)
        self.assertNotIn("cp build/rime-package/*.yaml", section)


if __name__ == "__main__":
    unittest.main()
